name: Terraform apply
run-name: Create application k8s infra
on:
  push:
    branches:
      - main      # Apenas on push na main (PR aceito)

jobs:
  terraform-apply:
    uses: ./.github/workflows/_run-terraform-command.yml
    with:
      TERRAFORM_COMMAND: apply --auto-approve

      AWS_REGION: us-east-1
      TF_STATE_BUCKET_NAME: ${{vars.TF_STATE_BUCKET_NAME}}
      TF_STATE_BUCKET_PATH: ${{vars.TF_STATE_BUCKET_PATH}}
      TF_LOCK_TABLE_NAME: ${{vars.TF_LOCK_TABLE_NAME}}
    secrets: inherit
